### ISSUE TITLE
can not have two curves with the same time shift

### ISSUE THREAD

**Issue by mike38** [leoswing/comparequeries-datasource-rc#10]
In order to  combine two style of curve, I would need to have two curves, with different labels, but with the same timeshift. It does not seem to be possible. Is it a limitation or something that can be available? 
![image](https://github.com/user-attachments/assets/f6012ae6-56fc-4742-88ed-d4b477689c68)

**Comment by leoswing** [comment]
> In order to combine two style of curve, I would need to have two curves, with different labels, but with the same timeshift. It does not seem to be possible. Is it a limitation or something that can be available? ![image](https://private-user-images.githubusercontent.com/2010717/351215343-f6012ae6-56fc-4742-88ed-d4b477689c68.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE3MTc3NzIsIm5iZiI6MTcyMTcxNzQ3MiwicGF0aCI6Ii8yMDEwNzE3LzM1MTIxNTM0My1mNjAxMmFlNi01NmZjLTQ3NDItODhlZC1kNGI0Nzc2ODljNjgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MjNUMDY1MTEyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZGUzMTVkZWJkNDVjYjA2NTkyNDY5NjFhOWQyNzdhYjllNjgyZDRlM2IxMmM2MDUxYWQzZDE4MDM0NTUyNWJjOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.yQaC5T_05-6N61TYLwQH1hsc_zZ9PCLsrBBCqNJoTFI)

Using the same timeShift amount but with different label, would result in the override label of the curve. This is a limitation of Grafana itself, demo tips could follow as below:

<img width="1213" alt="image" src="https://github.com/user-attachments/assets/d2cbca60-8c39-4cf1-bb6a-a5a50975d2b6">

**Comment by mike38** [comment]
thanks for this quick answer. May you have a tip to prevent that?

**Comment by leoswing** [comment]
> thanks for this quick answer. May you have a tip to prevent that?

Hi mike, same timeShift amount in one plugin or cross two compareQueries plugin settings,  would restict to the same override effect, so in these two separate plugin instance, it's hard to detect and prevent.

So for the input field of two separate plugin instance, the `QueryEditor` did not detect the existence of the same timeShift.

<img width="775" alt="image" src="https://github.com/user-attachments/assets/08f090b1-8e24-4607-a169-1656deb05fea">

**Comment by leoswing** [comment]
Close issue due to completed.
