### ISSUE TITLE
Dashboards: Comparing with Multiple Fields Results in Identical Field Names in Comparison Output

### ISSUE THREAD

**Issue by leo-6C656F** [leoswing/comparequeries-datasource-rc#11]
### What happened?

When performing a comparison query with more than one field, the resulting field names in the comparison query output are look to be incorrect.

1. The time field retains its correct name and is properly suffixed as expected in comparison results.
2. For all other fields, the comparison query applies the field name from the first column to subsequent columns.

<img width="857" alt="image" src="https://github.com/user-attachments/assets/cbed98f9-aca1-43c0-80c3-f9d0b0837afe">
<img width="857" alt="image" src="https://github.com/user-attachments/assets/526ff3e8-ec3e-4889-8b50-32f1795d2f93">

### What did you expect to happen?

Each field should properly map with he correct suffix. 

### Did this work before?

No

### How do we reproduce it?

1. Create query with more than one field, ex. time, transaction, dollar_amount
2. Start Comparison Query

### Environment (with versions)?

Grafana: v11.2.0 (c57667e448)

### Grafana platform?

Docker

**Comment by leoswing** [comment]
@leo-6C656F  Hi , Could you please help to  provide the full detail snapshots ? As I use in the Grafana 11.2.2, it works fine.

Environment (with versions)
Grafana: v11.2.2

Plugin version:
2.0.2

<img width="1284" alt="image" src="https://github.com/user-attachments/assets/3d187f8c-2c33-4876-906c-d96623f1b65c">

**Comment by leoswing** [comment]
@leo-6C656F Hi leo, is there any problem about this issue? If no, I will close this in a few days ~

**Comment by beyzacevik** [comment]
Hello, 

@leoswing Thank you for your contribution.

I think it is also a problem for grafana 11.3.. There are some buggy situations in naming of the variables. 

E.g 1: Even though I use the absolute prefix it does adds the '2' to the end of the variable. 
![Screenshot 2024-11-13 134353](https://github.com/user-attachments/assets/9c74e3e1-84f1-4227-9465-705f7935105b)


E.g 2: Although the functionality is correct on my implementation on board. The variable naming is not working correctly. It raises the below error:

![Screenshot 2024-11-13 134611](https://github.com/user-attachments/assets/c66f61b3-7e52-4d57-b5e1-8e49ff6ae444)
![Screenshot 2024-11-13 134638](https://github.com/user-attachments/assets/a661378b-3133-45e5-8423-0eefd0496c7d)



Note: I am 100% sure of the reason for the second problem. I can create another issue if required. 

Thanks

**Comment by leoswing** [comment]
@beyzacevik Hi, I've been using the plugin under Grafana 11.2.2 whent plugin version 2.0.2, I will check how it's performed in Grafana 11.3.0. 

May I know which version of plugin is using in your production?

**Comment by leoswing** [comment]
> @leoswing
> 
> Here are the versions for reproduction:
> 
> Grafana: Grafana v11.3.0-pre (unknown-de) CompareQueries: leoswing-comparequeries-datasource-2.0.2

<img width="1305" alt="截屏2024-11-18 16 58 42" src="https://github.com/user-attachments/assets/8aecb1a8-0cf9-4c34-9a6e-5f4f0358f2ab">

@beyzacevik Hi, I just tested in Grafana 11.3.0 release version with plugin 2.0.2, and it just works fine.

And my database is ElasticSearch, the field name in comparison result works as expect.

**Comment by leoswing** [comment]
@beyzacevik The second issue which raise error does not comes from this plugin. 
And meanwhile the first naming field issue just caused under absolute mode. After debug found that this may due to Grafana 11 may using the absolute value as the default one, so when it's named as the same, it would produce the 2 in the absolute mode.

**Comment by leoswing** [comment]
@leo-6C656F @beyzacevik Hi, I've fixed this, and submit a new version submission, now waiting for grafana reviews. Thanks for you using this plugin~ 

And welcome to star ～

**Comment by beyzacevik** [comment]
@leoswing Hello, thank you so much for the care for this issue. I will try it out with the new version. Also, I realized that the first issue was related to elasticsearch plugin permissions.

**Comment by leoswing** [comment]
@leo-6C656F @beyzacevik Hi guys, plugin version 2.0.3 is released which fix the field name display issue, and works well.

Could you please update and use the latest version 2.0.3 for the plugin? Thanks for your reporting.
