### ISSUE TITLE
多个es query添加compare时，如果时间偏移量一致只显示最后一个compare的数据

### ISSUE THREAD

**Issue by chnchi** [leoswing/comparequeries-datasource-rc#18]
### What happened?

1. 配置2条ES查询的query，A为2XX，B为4XX
2. 分别添加2条A和B的compare querys
3. 如果2条compare querys的time shift配置为不同的时间，如一个是1h另一个是2h，则两个compare querys都可以正常显示
![WX20241213-175202@2x](https://github.com/user-attachments/assets/73a0dac6-5eb9-4509-bb94-13a996867c7c)

4. 如果2条compare querys的time shift配置为相同的时间，如都是1h，则只显示最后一条compare query的数据（4XX 1h）
![WX20241213-175444@2x](https://github.com/user-attachments/assets/35f3b361-e8e6-48cb-99db-fa23b3cfe583)

### What did you expect to happen?

多个compare querys的数据都可以正常显示

### Did this work before?

无

### How do we reproduce it?

1.配置2条es查询语句
2.分别配置这两条es query的compare querys
3.compare querys配置相同的time shift

### Environment (with versions)?

Grafana: v11.2.0 (c57667e448)
OS: CentOS
Browser: chrome

### Grafana platform?

A package manager (APT, YUM, BREW, etc.)

**Comment by leoswing** [comment]
@chnchi TimeShift with the same value passed in will result in the same data points by grafana query.
> This behavior is controlled by Grafana data query flow.

Issue will close if no other issue occurs.

**Comment by chnchi** [comment]
> @chnchi TimeShift with the same value passed in will result in the same data points by grafana query.
> 
> > This behavior is controlled by Grafana data query flow.
> 
> Issue will close if no other issue occurs.

这个是新版本grafana的变动吗？
我用9.1.x版本的grafana和 https://github.com/AutohomeCorp/autohome-compareQueries-datasource 这个插件，同样的配置显示是正常的

<img width="1641" alt="image" src="https://github.com/user-attachments/assets/17b343e0-bf7e-4dcf-846b-0097b8af9b26" />

**Comment by leoswing** [comment]
> > @chnchi TimeShift with the same value passed in will result in the same data points by grafana query.
> > > This behavior is controlled by Grafana data query flow.
> > 
> > 
> > Issue will close if no other issue occurs.
> 
> 这个是新版本grafana的变动吗？ 我用9.1.x版本的grafana和 https://github.com/AutohomeCorp/autohome-compareQueries-datasource 这个插件，同样的配置显示是正常的
> 
> <img alt="image" width="1641" src="https://private-user-images.githubusercontent.com/30403780/395527754-17b343e0-bf7e-4dcf-846b-0097b8af9b26.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQwODYzODksIm5iZiI6MTczNDA4NjA4OSwicGF0aCI6Ii8zMDQwMzc4MC8zOTU1Mjc3NTQtMTdiMzQzZTAtYmY3ZS00ZGNmLTg0NmItMDA5N2I4YWY5YjI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjEzVDEwMzQ0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAwY2MzNDQ2MDJlY2E5MTA4NDA1ZDU2Y2NkYWFmMTFjYzc4YmRlMGI2MzhjYzUxZGY1ZjNmOGE4Y2U3MGRmZDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.MiW59TRHbl8UPhGEsO5m6f54h1LRJ2EoGJH12F0OHXs">

Yep, with Grafana 9 and this plugin `leoswing-comparequeries-datasource`, you can get the same query result.

After upgrade to Grafana 10 and 11, the data query flow behavior is changed inside.

**Comment by chnchi** [comment]
> Yep, with Grafana 9 and this plugin `leoswing-comparequeries-datasource`, you can get the same query result.
> 
> After upgrade to Grafana 10 and 11, the data query flow behavior is changed inside.

收到，感谢～

**Comment by leoswing** [comment]
close due to completed.

**Comment by leoswing** [comment]
> > Yep, with Grafana 9 and this plugin `leoswing-comparequeries-datasource`, you can get the same query result.
> > After upgrade to Grafana 10 and 11, the data query flow behavior is changed inside.
> 
> 收到，感谢～

@chnchi Hi chn,  Grafana 9.x using with plugin `leoswing-comparequeries-datasource` also works fine with the same timeShift value settings. Grafana 10 and 11 change its datapoints calculation behavior with breaking change. 

<img width="2285" alt="image" src="https://github.com/user-attachments/assets/15cf04d5-4e57-4c1c-a1e5-269c931ff8d4" />
