### ISSUE TITLE
InfluxDB data source does not show data

### ISSUE THREAD

**Issue by mspaehn** [leoswing/comparequeries-datasource-rc#2]
First of all: kudos for migrating this plugin to react. I migrated from [autohome-compareQueries-datasource](https://github.com/AutohomeCorp/autohome-compareQueries-datasource) since it stopped working recently and had a setup with influxDB time series (temperature data) working before.

Unfortunately, for me, influxDB data source is not working with this plugin. See the following screenshot:
![image](https://github.com/leoswing/autohome-compareQueries-datasource-rc/assets/50263114/a0721823-ee98-4e04-bb69-2843a3cd3637)

When I switch back to the influxDB data source, the same query works fine:
![image](https://github.com/leoswing/autohome-compareQueries-datasource-rc/assets/50263114/dd6cde1c-876b-4be4-84c0-017161556388)

Any restrictions for influxDB data sources? Anything that I could try to resolve the issue? The only thing I can see in the Query Inspector is this:

![image](https://github.com/leoswing/autohome-compareQueries-datasource-rc/assets/50263114/f3286f75-1ba1-45b1-be88-7ec0b038249a)

Installed versions:
autohome-compareQueries-datasource-rc version 1.1.0
Grafana v11.0.0 (83b9528bce)

Using grafana and influxDB both via Docker.

Thanks in advance!

**Comment by leoswing** [comment]
<img width="842" src="https://github.com/leoswing/autohome-compareQueries-datasource-rc/assets/17714673/33fd8800-7693-4dc7-8471-ff9f505d1b06">
Hi, you should fill with the compareQueries rows field as the image shown above, the important field you should fill in:

- Query: This input field should refer to the query identifier, for your case, it should fill with:  A
- Amount: The timeShift number which you want to handle with, for example: 1d

**Query** field is important when you want compareQueries work, it retrieves the field input and execute the Query.  If you have multiple query, you should fill this field with your base Query identifier
**Amount** field is also important and should be filled in, it points out which timeShift you want to execute, the measure options support:  s(second), m(minute), h(hour), d(day), w(week), M(month), y(year)

Everything should go well after you've done the two fields input, and the data dashboard will show out.

**Comment by leoswing** [comment]
<img  src="https://github.com/leoswing/autohome-compareQueries-datasource-rc/assets/17714673/b1bd5106-928c-4eca-971b-8c506320d9d8">
Here is what I done with Elasticsearch, query with your base **Query** and fill in with **Amount**

Could you please help to do the actions like above? It wold work seems other teams also using InfluxDB, but you should first fill the compareQueries fields:  **Query** and **Amount**

@mspaehn Much appriciate if you could make the actions above

**Comment by leoswing** [comment]
> First of all: kudos for migrating this plugin to react. I migrated from [autohome-compareQueries-datasource](https://github.com/AutohomeCorp/autohome-compareQueries-datasource) since it stopped working recently and had a setup with influxDB time series (temperature data) working before.
> 
> Unfortunately, for me, influxDB data source is not working with this plugin. See the following screenshot: ![image](https://private-user-images.githubusercontent.com/50263114/341885813-a0721823-ee98-4e04-bb69-2843a3cd3637.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkwMTc1MDQsIm5iZiI6MTcxOTAxNzIwNCwicGF0aCI6Ii81MDI2MzExNC8zNDE4ODU4MTMtYTA3MjE4MjMtZWU5OC00ZTA0LWJiNjktMjg0M2EzY2QzNjM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIyVDAwNDY0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUyNTFiNGY1ZTE2MDUwYjM0ZGQ0MWYxYTM1NDIxMzQ1MmRjNmE4ZTJjYzU4OGExYWNkZjJjYmM4OWM2ZjZmNGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GuM9jw-t5713mebjs1e-u7gqGsbMdAdsHTTByV2yfRg)
> 
> When I switch back to the influxDB data source, the same query works fine: ![image](https://private-user-images.githubusercontent.com/50263114/341885994-dd6cde1c-876b-4be4-84c0-017161556388.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkwMTc1MDQsIm5iZiI6MTcxOTAxNzIwNCwicGF0aCI6Ii81MDI2MzExNC8zNDE4ODU5OTQtZGQ2Y2RlMWMtODc2Yi00YmU0LTg0YzAtMDE3MTYxNTU2Mzg4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIyVDAwNDY0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNmYjI2ZDI5YmRmZmViYzBhZDM3ZmJlZTc4Mzk3NzczZmY4YzJmOWUyZDRhZWI4NjljNDc5ZmZlN2QyMGU5ZmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.H8oe4ydBG0xbQR5zQ7bkwG-LoQDwP1fksX8JEaklwCQ)
> 
> Any restrictions for influxDB data sources? Anything that I could try to resolve the issue? The only thing I can see in the Query Inspector is this:
> 
> ![image](https://private-user-images.githubusercontent.com/50263114/341886338-f3286f75-1ba1-45b1-be88-7ec0b038249a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkwMTc1MDQsIm5iZiI6MTcxOTAxNzIwNCwicGF0aCI6Ii81MDI2MzExNC8zNDE4ODYzMzgtZjMyODZmNzUtMWJhMS00NWIxLWJlODgtN2VjMGIwMzgyNDlhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIyVDAwNDY0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRjOTU4ZTY1MTcwYzk4Mjc1YzJlZDUwZmU3YWExYjc5ZDg4ZWU4OTU4OTIzMmFjNTlhMDEyZjg2MDBjYWIzZDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ujL6achTw_h7pZvTNBjW4_oo5PkNoMWy39MgVZm1YXY)
> 
> Installed versions: autohome-compareQueries-datasource-rc version 1.1.0 Grafana v11.0.0 (83b9528bce)
> 
> Using grafana and influxDB both via Docker.
> 
> Thanks in advance!

By the way,  @mspaehn  could you please help to check the steps:

- Have already restart the grafana docker instance?
- First you need to disabled old version in Grafana / Plugins / uninstall
- Have you restart Grafana server after installing or removing plugins?

**Comment by mspaehn** [comment]
Hi @leoswing,

thanks for your quick support!

First feedback: Somehow it now just worked after waiting 2 days! 🎉

Now to the issue:
I had already the query referenced in but took the screenshot after trying around a bit. Now the query inspector also shows some requests:

![image](https://github.com/leoswing/autohome-compareQueries-datasource-rc/assets/50263114/6c5dc165-83a7-46e4-998e-3a0cf351d33e)

I am still not fully understanding what I missed and why it now works.
* Have already restart the grafana docker instance?
  [X] Yes, via Portainer
* First you need to disabled old version in Grafana / Plugins / uninstall
  [X] Yes, I disabled the old plugin version and removed the folder from the plugins directory
* Check the permission of /var/lib/grafana/plugins/, and you could RUN chmod -R 755 /var/lib/grafana/plugins/ if no permission is granted
  [X] Yes, I performed chmod -R 755 and even the owner was set correctly.
* Have you restart Grafana server after installing or removing plugins?
  [X] Yes, I restarted the Docker container via Portainer

One guess that I have now: On Sundays, I perform automatic updates via Watchtower on all my Docker images and the Grafana image was updated. Either the new version or just the fact that the image was freshly deployed could have fixed my issue?

**Comment by mspaehn** [comment]
Interestingly, I found now that after saving and leaving the chart and coming back, the time shifts seem to be lost in the settings but the time series are still there. I am very much confused, why that happens. Also a full refresh didn't change the appearance.

![image](https://github.com/leoswing/autohome-compareQueries-datasource-rc/assets/50263114/dc4615c8-2735-4c18-9f43-88700b767c81)

**Comment by leoswing** [comment]
> Interestingly, I found now that after saving and leaving the chart and coming back, the time shifts seem to be lost in the settings but the time series are still there. I am very much confused, why that happens. Also a full refresh didn't change the appearance.
> 
> ![image](https://private-user-images.githubusercontent.com/50263114/342246922-dc4615c8-2735-4c18-9f43-88700b767c81.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyMTU4NzcsIm5iZiI6MTcxOTIxNTU3NywicGF0aCI6Ii81MDI2MzExNC8zNDIyNDY5MjItZGM0NjE1YzgtMjczNS00YzE4LTlmNDMtODg3MDBiNzY3YzgxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI0VDA3NTI1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdhOTVhNmFjMTI0YjA0NWY0OTlhZjM2YzQyMjk1YmRiNzExODc5N2IxN2M4NTJhNDRlNzE4ZTdmMDI1NGY0Y2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.i1nGTF4YUvzE0ve_RWLU01VFzVyUJ8VzWaZId0bIYhY)

@mspaehn Sorry about the bug, I also found this issue, the fix version is released with the [PR](https://github.com/leoswing/autohome-compareQueries-datasource-rc/pull/3)

You could use the release version [1.2.0](https://github.com/leoswing/autohome-compareQueries-datasource-rc/releases/download/1.2.0/autohome-comparequeries-datasource.zip) , and version tag [1.2.0](https://github.com/leoswing/autohome-compareQueries-datasource-rc/releases/tag/1.2.0) has solved the issue

**Comment by leoswing** [comment]
@mspaehn Hi, sorry about that. Could you please help to use the latest fix version [1.2.0](https://github.com/leoswing/autohome-compareQueries-datasource-rc/releases/tag/1.2.0) to replace with the old version? This version solve the issue and works well.

**Comment by mspaehn** [comment]
Unfortunately, just replacing the plugin folder with version 1.2.0 and restarting the Docker container (via Portainer and via `docker restart XXX` did not help for me. Do I have to consider something else?

**Comment by leoswing** [comment]
> Unfortunately, just replacing the plugin folder with version 1.2.0 and restarting the Docker container (via Portainer and via `docker restart XXX` did not help for me. Do I have to consider something else?

Hi, maybe you can check your docker instance in folder: `/var/lib/grafana/plugins`, and find whether the plugin version has upgrade.

**Comment by leoswing** [comment]
> Unfortunately, just replacing the plugin folder with version 1.2.0 and restarting the Docker container (via Portainer and via `docker restart XXX` did not help for me. Do I have to consider something else?

@mspaehn Could you help to check the plugin version inside docker instance folder? The plugin would be located in folder `/var/ib/grafana/plugins`, and you can check the file under the folder with name `plugin.json` and the entry file `module.js`

**Comment by mspaehn** [comment]
@leoswing I checked the plugin version with your guidance and it is version 1.2.0. After waiting two days, it now magically works again. I assume the issues that I have might be related to some sort of caching. I am using Nginx Proxy Manager as reverse proxy with "Cache assets" option enabled.

Thank you for your great support! This issue can be closed now.

**Comment by leoswing** [comment]
> @leoswing I checked the plugin version with your guidance and it is version 1.2.0. After waiting two days, it now magically works again. I assume the issues that I have might be related to some sort of caching. I am using Nginx Proxy Manager as reverse proxy with "Cache assets" option enabled.
> 
> Thank you for your great support! This issue can be closed now.

@mspaehn Hi , you can now use the latest version 2.0.1 with public sinature support, it's signed in Grafana with id  `eoswing-comparequeries-datasource`, details you could refer to the link below:

https://grafana.com/grafana/plugins/leoswing-comparequeries-datasource/

**Comment by mspaehn** [comment]
Dear @leoswing,

congratulations for bringing this plugin to the Grafan plugin store! Great job! 👏 

I tested it and everything works like a charm with my influxDB setup out of the box! 😃

**Comment by leoswing** [comment]
> Dear @leoswing,
> 
> congratulations for bringing this plugin to the Grafan plugin store! Great job! 👏
> 
> I tested it and everything works like a charm out of the box with my influxDB setup ! 😃

@mspaehn Nice ~ Hope everything works well.

**Comment by leoswing** [comment]
@mspaehn  Hi, I've released the 2.0.2 version, which supports the amount input field with variables. Could you please help to use the latest one? Much appreciated~
