### ISSUE TITLE
Signature: Version 2.0.0 claims to be signed, but it is unsigned

### ISSUE THREAD

**Issue by MiCRoPhoBIC** [leoswing/comparequeries-datasource-rc#7]
### What happened?

According to the changelog for version 2.0.0:

> Refactor the plugin id with `leoswing-comparequeries-datasource`, and signed with public signature level in Grafana.

However, all signed plugins must contain [MANIFEST.txt](https://grafana.com/developers/plugin-tools/publish-a-plugin/sign-a-plugin#plugin-manifest) in order Grafana to verify the digital signature of the plugin.
MANIFEST.txt is missing from the project.

### What did you expect to happen?

The plugin can be public, signed as Community or signed as Commercial. [What are the different classifications of plugins](https://grafana.com/legal/plugins/#what-are-the-different-classifications-of-plugins)

If the plugin cannot be signed (it is free) with signature level "Community" I believe it shouldn't be called Signed, because there isn't any signature at all and the plugin is simply not signed.

### Did this work before?

No

### How do we reproduce it?

1.
2.
3.

### Environment (with versions)?

Grafana:
OS:
Browser:

### Grafana platform?

None

**Comment by leoswing** [comment]
> ### What happened?
> According to the changelog for version 2.0.0:
> 
> > Refactor the plugin id with `leoswing-comparequeries-datasource`, and signed with public signature level in Grafana.
> 
> However, all signed plugins must contain [MANIFEST.txt](https://grafana.com/developers/plugin-tools/publish-a-plugin/sign-a-plugin#plugin-manifest) in order Grafana to verify the digital signature of the plugin. MANIFEST.txt is missing from the project.
> 
> ### What did you expect to happen?
> The plugin can be public, signed as Community or signed as Commercial. [What are the different classifications of plugins](https://grafana.com/legal/plugins/#what-are-the-different-classifications-of-plugins)
> 
> If the plugin cannot be signed (it is free) with signature level "Community" I believe it shouldn't be called Signed, because there isn't any signature at all and the plugin is simply not signed.
> 
> ### Did this work before?
> No
> 
> ### How do we reproduce it?
> 
> ### Environment (with versions)?
> Grafana: OS: Browser:
> 
> ### Grafana platform?
> None

That's correct, it's wating for reviewing, sorry for report that declaration mistake, I've updated the README docs.

And I've create the post on Grafana community, when the plugin is signed I will update the status on repost in issue and README.

**Comment by MiCRoPhoBIC** [comment]
Thank you, much appreciated!

**Comment by leoswing** [comment]
Hi @MiCRoPhoBIC , this plugin has been published in Grafana plugins with signature ~ welcome to use this signed plugin ~

Plugin details you could refer to the website: https://grafana.com/grafana/plugins/leoswing-comparequeries-datasource/

**Comment by MiCRoPhoBIC** [comment]
Great news! Thank you!

**Comment by MisterMartin** [comment]
The new plugin works great. Being signed and served by grafana is huge. Thanks!

**Comment by leoswing** [comment]
@MisterMartin @MiCRoPhoBIC Hi, I've updated this plugin with version 2.0.2, could you please help to use the latest one?

In this new version, I've fixed the amount field with variable support~

**Comment by leoswing** [comment]
@matejanajdanov @cpmoore @szerwi  Hi~ sorry to interrupt you all. By the way, with timeShift per query ability in single dashboard panel, you could use this plugin with version 2.0.2, posts link to [ issue](https://github.com/grafana/grafana/issues/22942).

**Comment by leoswing** [comment]
@szerwi @matejanajdanov @cpmoore Hi, sorry to interrupt you all. By the way, with Grafana timeshift per query in single panel ability, you could use this plugin as alternative choice~ May this plugin could help you in some way~
